### ISSUE TITLE
Run the topmed workflows

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/team-lighthouse-point#160]

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

Debugging Alignment:

Environment

  * Google VM running Ubuntu 16

Installation

  * jdk 9
  * docker

Connect to google

gcloud compute \-\-project "platform-dev-178517" ssh \-\-zone "us-east4-c" "brian-topmed-workflow-testing" 

Alignment

[https://github.com/DataBiosphere/topmed-workflows/blob/master/aligner/u_of_michigan_aligner/u_of_michigan_aligner.wdl](https://github.com/DataBiosphere/topmed-workflows/blob/master/aligner/u_of_michigan_aligner/u_of_michigan_aligner.wdl)

Variant Calling

[https://github.com/DataBiosphere/topmed-workflows/tree/master/variant-caller](https://github.com/DataBiosphere/topmed-workflows/tree/master/variant-caller)

Reference workflows from Goncalo

[https://github.com/statgen/topmed_freeze3_calling](https://github.com/statgen/topmed_freeze3_calling)

and 

[https://github.com/statgen/topmed-alignment](https://github.com/statgen/topmed-alignment)

Reference files in GCloud

[https://console.cloud.google.com/storage/browser/topmed_workflow_testing/?project=platform-dev-178517&authuser=1](https://console.cloud.google.com/storage/browser/topmed_workflow_testing/?project=platform-dev-178517&authuser=1)

Alignment

Trying it out with a small-ish CRAM input

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ time java \-jar \~/cromwell/cromwell-31.jar run u_of_michigan_aligner.wdl \-i my_u_of_michigan_aligner.json 

The Error: 

\[2018-05-18 15:44:11,14\] \[info\] BackgroundConfigAsyncJobExecutionActor \[1b2d6705TopMedAligner.PreAlign:NA:1\]: executing: d 

ocker run \ 

\-\-cidfile /home/boconnor/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner/cromwell-executions/TopMed 

Aligner/1b2d6705-ed7d-4537-b36b-96fa646fc85f/call-PreAlign/execution/docker_cid \ 

\-\-rm \-i \ 

\ 

\-\-entrypoint /bin/bash \ 

\-v /home/boconnor/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner/cromwell-executions/TopMedAligner 

/1b2d6705-ed7d-4537-b36b-96fa646fc85f/call-PreAlign:/cromwell-executions/TopMedAligner/1b2d6705-ed7d-4537-b36b-96fa646fc85 

f/call-PreAlign \ 

statgen/alignment /cromwell-executions/TopMedAligner/1b2d6705-ed7d-4537-b36b-96fa646fc85f/call-PreAlign/execution/script 

\[2018-05-18 15:44:15,58\] \[info\] BackgroundConfigAsyncJobExecutionActor \[1b2d6705TopMedAligner.PreAlign:NA:1\]: job id: 2725 

2 

\[2018-05-18 15:44:15,58\] \[info\] BackgroundConfigAsyncJobExecutionActor \[1b2d6705TopMedAligner.PreAlign:NA:1\]: Status chang 

e from \- to WaitingForReturnCodeFile 

\[2018-05-18 15:46:11,13\] \[error\] key not found: DockerHashRequest(DockerImageIdentifierWithoutHash(None,Some(statgen),alig 

nment,latest),List()) 

java.util.NoSuchElementException: key not found: DockerHashRequest(DockerImageIdentifierWithoutHash(None,Some(statgen),ali 

gnment,latest),List()) 

... 

\[2018-05-18 15:46:11,15\] \[error\] WorkflowManagerActor Workflow 1b2d6705-ed7d-4537-b36b-96fa646fc85f failed (during Executi 

ngWorkflowState): key not found: DockerHashRequest(DockerImageIdentifierWithoutHash(None,Some(statgen),alignment,latest),L 

ist()) 

java.util.NoSuchElementException: key not found: DockerHashRequest(DockerImageIdentifierWithoutHash(None,Some(statgen),ali 

gnment,latest),List()) 

... 

\[2018-05-18 15:47:40,58\] \[info\] WorkflowLogCopyRouter stopped 

\[2018-05-18 15:47:40,58\] \[info\] JobExecutionTokenDispenser stopped 

\[2018-05-18 15:47:40,58\] \[info\] Shutting down WorkflowManagerActor \- Timeout = 3600000 milliseconds 

\[2018-05-18 15:47:40,58\] \[info\] WorkflowManagerActor stopped 

\[2018-05-18 15:47:40,58\] \[info\] Connection pools shut down 

\[2018-05-18 15:47:45,59\] \[info\] Shutting down SubWorkflowStoreActor \- Timeout = 1800000 milliseconds 

\[2018-05-18 15:47:45,59\] \[warn\] Coordinated shutdown phase \[service-stop\] timed out after 5000 milliseconds 

\[2018-05-18 15:47:45,59\] \[info\] Shutting down JobStoreActor \- Timeout = 1800000 milliseconds 

\[2018-05-18 15:47:45,59\] \[info\] Shutting down CallCacheWriteActor \- Timeout = 1800000 milliseconds 

\[2018-05-18 15:47:45,59\] \[info\] Shutting down ServiceRegistryActor \- Timeout = 1800000 milliseconds 

\[2018-05-18 15:47:45,59\] \[info\] Shutting down DockerHashActor \- Timeout = 1800000 milliseconds 

\[2018-05-18 15:47:45,59\] \[info\] Shutting down IoProxy \- Timeout = 1800000 milliseconds 

\[2018-05-18 15:47:45,59\] \[info\] SubWorkflowStoreActor stopped 

\[2018-05-18 15:47:45,59\] \[info\] JobStoreActor stopped 

\[2018-05-18 15:47:45,59\] \[info\] CallCacheWriteActor stopped 

\[2018-05-18 15:47:45,59\] \[info\] ServiceRegistryActor stopped 

\[2018-05-18 15:47:45,59\] \[info\] DockerHashActor stopped 

\[2018-05-18 15:47:45,59\] \[info\] IoProxy stopped 

\[2018-05-18 15:47:45,60\] \[info\] Database closed 

\[2018-05-18 15:47:45,61\] \[info\] Stream materializer shut down 

\[2018-05-18 15:47:45,61\] \[error\] Outgoing request stream error 

akka.stream.AbruptTerminationException: Processor actor \[Actor\[akka://cromwell-system/user/StreamSupervisor-1/flow-3-0-mergePreferred\#\-955960197\]\] terminated abruptly 

\[2018-05-18 15:47:45,61\] \[error\] Outgoing request stream error 

akka.stream.AbruptTerminationException: Processor actor \[Actor\[akka://cromwell-system/user/StreamSupervisor-1/flow-3-0-mergePreferred\#\-955960197\]\] terminated abruptly 

\[2018-05-18 15:47:45,61\] \[error\] Outgoing request stream error 

akka.stream.AbruptTerminationException: Processor actor \[Actor\[akka://cromwell-system/user/StreamSupervisor-1/flow-3-0-mergePreferred\#\-955960197\]\] terminated abruptly 

real    8m51.922s 

user    0m47.914s 

sys     0m3.237s 

Locally

cat my_u_of_michigan_aligner.json 

\{ 

"TopMedAligner.input_cram_file": "/home/boconnor/TopMed/topmed_open_access/NWD176325.025percent.recab.cram", 

"TopMedAligner.input_crai_file": "/home/boconnor/TopMed/topmed_open_access/NWD176325.025percent.recab.cram.crai", 

"TopMedAligner.ref_alt":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.alt](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.alt)", 

"TopMedAligner.ref_bwt":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.bwt](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.bwt)", 

"TopMedAligner.ref_pac":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.pac](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.pac)", 

"TopMedAligner.ref_ann":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.ann](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.ann)", 

"TopMedAligner.ref_amb":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.amb](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.amb)", 

"TopMedAligner.ref_sa":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.sa](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.sa)", 

"TopMedAligner.ref_fasta":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa)", 

"TopMedAligner.ref_fasta_index":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.fai](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.fai)", 

"TopMedAligner.dbSNP_vcf": "/home/boconnor/TopMed/Homo_sapiens_assembly38.dbsnp138.vcf.gz", 

"TopMedAligner.dbSNP_vcf_index": "/home/boconnor/TopMed/Homo_sapiens_assembly38.dbsnp138.vcf.gz.tbi", 

"TopMedAligner.docker_image": "statgen/alignment:latest" 

\} 

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ cat my_u_of_michigan_aligner.2.json 

\{ 

"TopMedAligner.input_cram_file": "/home/boconnor/TopMed/topmed_open_access/NWD176325.0005.recab.cram", 

"TopMedAligner.input_crai_file": "/home/boconnor/TopMed/topmed_open_access/NWD176325.0005.recab.cram.crai", 

"TopMedAligner.ref_alt":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.alt](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.alt)", 

"TopMedAligner.ref_bwt":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.bwt](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.bwt)", 

"TopMedAligner.ref_pac":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.pac](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.pac)", 

"TopMedAligner.ref_ann":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.ann](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.ann)", 

"TopMedAligner.ref_amb":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.amb](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.amb)", 

"TopMedAligner.ref_sa":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.sa](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.sa)", 

"TopMedAligner.ref_fasta":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa)", 

"TopMedAligner.ref_fasta_index":  "/home/boconnor/topmed_freeze3_calling/data/[local.org/ref/gotcloud.ref/hg38/hs38DH.fa.fai](http://local.org/ref/gotcloud.ref/hg38/hs38DH.fa.fai)", 

"TopMedAligner.dbSNP_vcf": "/home/boconnor/TopMed/Homo_sapiens_assembly38.dbsnp138.vcf.gz", 

"TopMedAligner.dbSNP_vcf_index": "/home/boconnor/TopMed/Homo_sapiens_assembly38.dbsnp138.vcf.gz.tbi", 

"TopMedAligner.docker_image": "statgen/alignment:latest" 

\} 

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ cat my_u_of_michigan_aligner.3.json 

\{ 

"TopMedAligner.input_cram_file": "gs://topmed_workflow_testing/topmed_aligner/input_files/NWD176325.0005.recab.cram", 

"TopMedAligner.input_crai_file": "gs://topmed_workflow_testing/topmed_aligner/input_files/NWD176325.0005.recab.cram.crai", 

"TopMedAligner.ref_alt":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.alt", 

"TopMedAligner.ref_bwt":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.bwt", 

"TopMedAligner.ref_pac":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.pac", 

"TopMedAligner.ref_ann":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.ann", 

"TopMedAligner.ref_amb":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.amb", 

"TopMedAligner.ref_sa":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.sa", 

"TopMedAligner.ref_fasta":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa", 

"TopMedAligner.ref_fasta_index":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.fai", 

"TopMedAligner.dbSNP_vcf": "gs://topmed_workflow_testing/topmed_aligner/reference_files/hg38/Homo_sapiens_assembly38.dbsnp138.vcf.gz", 

"TopMedAligner.dbSNP_vcf_index": "gs://topmed_workflow_testing/topmed_aligner/reference_files/hg38/Homo_sapiens_assembly38.dbsnp138.vcf.gz.tbi", 

"TopMedAligner.docker_image": "[quay.io/ucsc_cgl/topmed_statgen_alignment:latest](http://quay.io/ucsc_cgl/topmed_statgen_alignment:latest)" 

\} 

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ cat my_u_of_michigan_aligner.4.json 

\{ 

"TopMedAligner.input_cram_file": "gs://topmed_workflow_testing/topmed_aligner/input_files/NWD176325.0005.recab.cram", 

"TopMedAligner.input_crai_file": "gs://topmed_workflow_testing/topmed_aligner/input_files/NWD176325.0005.recab.cram.crai", 

"TopMedAligner.ref_alt":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.alt", 

"TopMedAligner.ref_bwt":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.bwt", 

"TopMedAligner.ref_pac":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.pac", 

"TopMedAligner.ref_ann":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.ann", 

"TopMedAligner.ref_amb":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.amb", 

"TopMedAligner.ref_sa":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.sa", 

"TopMedAligner.ref_fasta":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa", 

"TopMedAligner.ref_fasta_index":  "gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.fai", 

"TopMedAligner.dbSNP_vcf": "gs://topmed_workflow_testing/topmed_aligner/reference_files/hg38/Homo_sapiens_assembly38.dbsnp138.vcf.gz", 

"TopMedAligner.dbSNP_vcf_index": "gs://topmed_workflow_testing/topmed_aligner/reference_files/hg38/Homo_sapiens_assembly38.dbsnp138.vcf.gz.tbi", 

"TopMedAligner.docker_image": "[gcr.io/platform-dev-178517/statgenalignment](http://gcr.io/platform-dev-178517/statgenalignment)" 

\} 

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ time java \-jar \~/cromwell/cromwell-31.jar run u_of_michigan_aligner.wdl \-i my_u_of_michigan_aligner.json

\[2018-05-21 10:09:55,91\] \[info\] WorkflowManagerActor WorkflowActor-f6ee5b54-63df-4668-8c7c-5065897fc10b is in a terminal state: WorkflowSucceededState 

\[2018-05-21 10:10:27,81\] \[info\] SingleWorkflowRunnerActor workflow finished with status 'Succeeded'. 

\{ 

"outputs": \{ 

"TopMedAligner.aligner_output": "/home/boconnor/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner/cromwell-executions/TopMedAligner/f6ee5b54-63df-4668-8c7c-5065897fc10b/call-PostAlign/execution/output_file.cram" 

\}, 

"id": "f6ee5b54-63df-4668-8c7c-5065897fc10b" 

\} 

real    21m7.549s 

user    1m9.792s 

sys     0m3.893s 

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ echo $? 

0 

Now trying with GS paths:

warning: 

Evaluating size(ref_alt, "GB") \+ size(ref_bwt, "GB") \+ size(ref_pac, "GB") \+ size(ref_ann, "GB") \+ size(ref_amb, "GB") \+ size(ref_sa, "GB") failed: java.lang.IllegalArgumentException: gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.alt exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: LinuxFileSystem. Please refer to the documentation for more information on how to configure filesystems: [http://cromwell.readthedocs.io/en/develop/backends/HPC/\#filesystems](http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems) 

java.lang.RuntimeException: Evaluating size(ref_alt, "GB") \+ size(ref_bwt, "GB") \+ size(ref_pac, "GB") \+ size(ref_ann, "GB") \+ size(ref_amb, "GB") \+ size(ref_sa, "GB") failed: java.lang.IllegalArgumentException: gs://topmed_workflow_testing/topmed_variant_caller/reference_files/hg38/hs38DH.fa.alt exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: LinuxFileSystem. Please refer to the documentation for more information on how to configure filesystems: [http://cromwell.readthedocs.io/en/develop/backends/HPC/\#filesystems](http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems) 

See [https://gatkforums.broadinstitute.org/wdl/discussion/11757/exists-on-a-filesystem-not-supported-by-this-instance-of-cromwell](https://gatkforums.broadinstitute.org/wdl/discussion/11757/exists-on-a-filesystem-not-supported-by-this-instance-of-cromwell) 

Need to set the API access on the VM at launch time: [https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#using](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#using) 

gcloud auth application-default login 

Now trying with GS paths via JES:

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ cat /home/boconnor/google.conf 

include required(classpath("application")) 

google \{ 

application-name = "cromwell" 

auths = \[ 

\{ 

name = "application-default" 

scheme = "application_default" 

\} 

\] 

\} 

engine \{ 

filesystems \{ 

gcs \{ 

auth = "application-default" 

\} 

\} 

\} 

backend \{ 

default = "JES" 

providers \{ 

JES \{ 

actor-factory = "cromwell.backend.impl.jes.JesBackendLifecycleActorFactory" 

config \{ 

// Google project 

project = "platform-dev-178517" 

// Base bucket for workflow executions 

root = "gs://topmed_workflow_testing_logs/cromwell-execution" 

// Polling for completion backs-off gradually for slower-running jobs. 

// This is the maximum polling interval (in seconds): 

maximum-polling-interval = 600 

// Optional Dockerhub Credentials. Can be used to access private docker images. 

dockerhub \{ 

// account = "" 

// token = "" 

\} 

genomics \{ 

// A reference to an auth defined in the `google` stanza at the top.  This auth is used to create 

// Pipelines and manipulate auth JSONs. 

auth = "application-default" 

// Endpoint for APIs, no reason to change this unless directed by Google. 

endpoint-url = "[https://genomics.googleapis.com/](https://genomics.googleapis.com/)" 

// This allows you to use an alternative service account to launch jobs, by default uses default service account 

compute-service-account = "default" 

\} 

filesystems \{ 

gcs \{ 

// A reference to a potentially different auth for manipulating files via engine functions. 

auth = "application-default" 

\} 

\} 

\} 

\} 

\} 

\} 

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ time java \-Dconfig.file=/home/boconnor/google.conf \-jar \~/cromwell/cromwell-31.jar run u_of_michigan_aligner.wdl \-i my_u_of_michigan_aligner.3.json 

Continued issue with Docker Pull

\[2018-05-21 12:04:35,64\] \[warn\] BackendPreparationActor_for_01481ba2:TopMedAligner.PreAlign:\-1:1 \[01481ba2\]: Docker lookup failed 

java.lang.Exception: Timeout looking up docker hash 

at cromwell.engine.workflow.WorkflowDockerLookupActor$$anonfun$5.applyOrElse(WorkflowDockerLookupActor.scala:115) 

at cromwell.engine.workflow.WorkflowDockerLookupActor$$anonfun$5.applyOrElse(WorkflowDockerLookupActor.scala:113) 

at scala.PartialFunction$OrElse.apply(PartialFunction.scala:168) 

at akka.actor.FSM.processEvent(FSM.scala:668) 

at akka.actor.FSM.processEvent$(FSM.scala:662) 

at cromwell.engine.workflow.WorkflowDockerLookupActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowDockerLookupActor.scala:39) 

at akka.actor.LoggingFSM.processEvent(FSM.scala:801) 

at akka.actor.LoggingFSM.processEvent$(FSM.scala:783) 

at cromwell.engine.workflow.WorkflowDockerLookupActor.processEvent(WorkflowDockerLookupActor.scala:39) 

at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659) 

at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653) 

at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) 

at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) 

at akka.actor.Actor.aroundReceive(Actor.scala:514) 

at akka.actor.Actor.aroundReceive$(Actor.scala:512) 

at cromwell.engine.workflow.WorkflowDockerLookupActor.aroundReceive(WorkflowDockerLookupActor.scala:39) 

at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) 

at akka.actor.ActorCell.invoke(ActorCell.scala:496) 

at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) 

at akka.dispatch.Mailbox.run(Mailbox.scala:224) 

at akka.dispatch.Mailbox.exec(Mailbox.scala:234) 

at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) 

at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) 

at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) 

at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) 

Trying to solve this with Google Container Registry

See [https://cloud.google.com/container-registry/docs/access-control#serving_images_publicly](https://cloud.google.com/container-registry/docs/access-control#serving_images_publicly)‌ and [https://cloud.google.com/container-registry/docs/pushing-and-pulling?hl=en_US&\_ga=2.182296610.\-428094956.1524843388](https://cloud.google.com/container-registry/docs/pushing-and-pulling?hl=en_US&_ga=2.182296610.-428094956.1524843388) 

I built on quay:  [https://quay.io/repository/ucsc_cgl/topmed_statgen_alignment?tab=builds](https://quay.io/repository/ucsc_cgl/topmed_statgen_alignment?tab=builds) 

I tried pushing to GCR: 

docker tag statgen/alignment [gcr.io/platform-dev-178517/statgenalignment](http://gcr.io/platform-dev-178517/statgenalignment) 

gcloud docker \-\- push [gcr.io/platform-dev-178517/statgenalignment](http://gcr.io/platform-dev-178517/statgenalignment) 

Running again:

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ time java \-Dconfig.file=/home/boconnor/google.conf \-jar \~/cromwell/cromwell-31.jar run u_of_michigan_aligner.wdl \-i my_u_of_michigan_aligner.3.json 

Final status of Alignment: FAILED on Google Cloud, OK locally (but not reliable?)

I could not figure out why Cromwell was failing on pull of the Docker image.  I tried hosting on DockerHub, [Quay.io](http://Quay.io) and the Google Container Registry.  None of them worked when running Cromwell via JES. 

\[2018-05-21 13:56:21,18\] \[error\] key not found: DockerHashRequest(DockerImageIdentifierWithoutHash(Some([gcr.io](http://gcr.io)),Some(platform-dev-178517),statgenalignment,latest),List(UserCredentials\{ 

and 

java.lang.Exception: Timeout looking up docker hash 

I think we need help from the Cromwell Broad experts.  To see if they've seen this before.  I wonder if the Docker pull is simply taking too long and this is a timeout issue with google pipelines API itself? 

This did work, however, when running locally.  I did see the pull problem, though.  Even when I know the image was already present locally.  But after a few tries this did work.  This does not inspire confidence, though, and is an indication of a lower-level problem I think.  Needs investigation with the Broad.

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

Trying via WES

boconnor@brian-topmed-workflow-testing:\~/gitroot/HumanCellAtlas/portability/external_executors/papi_cromwell/test/topmed_variant_caller$ sudo apt-get install httpie 

boconnor@brian-topmed-workflow-testing:\~/gitroot/HumanCellAtlas/portability/external_executors/papi_cromwell/test/topmed_variant_caller$ bash submit_to_wes.sh 

HTTP/1.1 200 OK 

Connection: keep-alive 

Content-Length: 55 

Content-Type: application/json 

Date: Mon, 21 May 2018 15:56:22 GMT 

Via: 1.1 [dbdd67063f01c39bd9e0f02db8431258.cloudfront.net](http://dbdd67063f01c39bd9e0f02db8431258.cloudfront.net) (CloudFront) 

X-Amz-Cf-Id: UcsZeFOSxp53CpNQMWwxxIYIzFv_zTMghAn6CemLS5eg9OTIzUnRYA== 

X-Amzn-Trace-Id: Root=1-5b02ec25-1f6de240666ec2e6f79adebc 

X-Cache: Miss from cloudfront 

x-amz-apigw-id: HPnV3F7toAMFpcg= 

x-amzn-RequestId: 819ea3a5-5d0f-11e8-8ecf-bd5a1bc59c17 

\{ 

"workflow_id": "d2d69d9d-9a23-4f8b-9f43-1f8c1d1fcdad" 

\} 

boconnor@brian-topmed-workflow-testing:\~/gitroot/HumanCellAtlas/portability/external_executors/papi_cromwell/test/topmed_variant_caller$ http GET "$WES_URL"/workflows/d2d69d9d-9a23-4f8b-9f43-1f8c1d1fcdad X-API-KEY:"$API_KEY" 

"state": "COMPLETE", 

"outputs": \{ 

"TopMedVariantCaller.topmed_variant_caller_output": "gs://broad-dsde-mint-dev-cromwell-execution/cromwell-executions/TopMedVariantCaller/d2d69d9d-9a23-4f8b-9f43-1f8c1d1fcdad/call-variantCalling/topmed_variant_caller_output.tar.gz" 

\}, 

Try Alignment

http POST "$WES_URL"/workflows workflow_descriptor=@topmed_freeze3_calling.wdl workflow_params:=@inputs.json X-API-KEY:"$API_KEY" 

boconnor@brian-topmed-workflow-testing:\~/gitroot/DataBiosphere/topmed-workflows/aligner/u_of_michigan_aligner$ http POST "$WES_URL"/workflows workflow_descriptor=@u_of_michigan_aligner.wdl workflow_params:=@my_u_of_michigan_aligner.3.json X-API-KEY:"$API_KEY" 

HTTP/1.1 200 OK 

Connection: keep-alive 

Content-Length: 55 

Content-Type: application/json 

Date: Mon, 21 May 2018 16:02:52 GMT 

Via: 1.1 73388[dc3c76783aef93703e1dfb340e2.cloudfront.net](http://dc3c76783aef93703e1dfb340e2.cloudfront.net) (CloudFront) 

X-Amz-Cf-Id: clrnPPhVJFnrMr9hkXOy_et2mXC2RnB3S9XESy7IpzJkvSckeD85dg== 

X-Amzn-Trace-Id: Root=1-5b02edac-c06517060ffcc85bbe69c92f 

X-Cache: Miss from cloudfront 

x-amz-apigw-id: HPoS7HWgIAMFXeA= 

x-amzn-RequestId: 6a8a051c-5d10-11e8-b8c5-01eba3a8a6df 

\{ 

"workflow_id": "0fd8711d-7d29-4d53-8470-4c6b83281450" 

\} 

http GET "$WES_URL"/workflows/0fd8711d-7d29-4d53-8470-4c6b83281450 X-API-KEY:"$API_KEY" 

"state": "COMPLETE", 

"outputs": \{ 

"TopMedAligner.aligner_output": "gs://broad-dsde-mint-dev-cromwell-execution/cromwell-executions/TopMedAligner/0fd8711d-7d29-4d53-8470-4c6b83281450/call-PostAlign/output_file.cram" 

\} 

STATUS: both alignment and variant calling workflows ran successfully through WES and reported output
