### ISSUE TITLE
Investigate why we cannot search for a file in boardwalk

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/team-lighthouse-point#307]
\| Repository: [*cgp-dashboard-service*](https://github.com/DataBiosphere/cgp-dashboard-service)

\| Pull-Request: [https://github.com/DataBiosphere/cgp-dashboard-service/pull/80](https://github.com/DataBiosphere/cgp-dashboard-service/pull/80)

A user can't search for a file in Boardwalk when using the File ID Search. The dropdown menu doesn't appear if the user types in the search box.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Seeing this error in logs:

2018-06-13 19:38:25,051 - dashboardService.elastic_request_builder.ElasticTransformDump - DEBUG - Printing ES_SEARCH request dict:
 {"sort": [{"_score.keyword": {"order": "desc"}}], "query": {"prefix": {"file_id.raw": "F123"}}, "from": 0, "size": 5}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webservice.py", line 274, in get_search
    entry_format=_type)
  File "./responseobjects/elastic_request_builder.py", line 546, in transform_autocomplete_request
    es_response = es_search.execute(ignore_cache=True)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/search.py", line 639, in execute
    **self._params
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [_score.keyword] in order to sort on')

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

Hi [~gpelayo1], based on the stack trace provided by [~coverbec], it looks like this may be a relatively easy fix.
Please take a look and let me know if you have questions (and/or when you think you know what the problem is).

Thanks!

**Comment by cricketsloan** [comment]
➤ Geryl Pelayo commented:

Sure [~mbaumann]. I'll see what I can do.
